#!/usr/bin/expect -f
# File    : jsphere_work
# Date    : 2013-02-08
# Author  : Tyler Christiansen <tyler@oss-stack.io>
# License : BSD 2-Clause (http://opensource.org/licenses/BSD-2-Clause)
# Purpose : jsphere expect script to log into Junosphere devices as
# Purpose :   root.

set host [lrange $argv 1 1]
set name [lrange $argv 0 0]

set timeout -1
send -- "echo -e '\033k$name\033\\'"
spawn ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@$host
match_max 100000
expect "password: "
send -- "Clouds\r"
expect "% "
send -- "cli\r"
expect "> "
interact

